package com.ers.exceptions;

public class InvalidStatusCodeException extends Exception {

	/**
	 * Generated Serial Version ID. Generated by Java.
	 */
	private static final long serialVersionUID = -1977060419190585605L;
	
	public InvalidStatusCodeException(String message) {
		super(message);
	}

}
