package com.ers.exceptions;

/**
 * User defined exception to be thrown if an invalid status code is used to
 * search a reimbursement.
 * 
 * @author Jose Rivera
 */
public class InvalidStatusCodeException extends Exception {

	/**
	 * Generated Serial Version ID. Generated by Java.
	 */
	private static final long serialVersionUID = -1977060419190585605L;

	/**
	 * Exception constructor to create an exception.
	 * 
	 * @param message The message to display that is sent to the super class.
	 */
	public InvalidStatusCodeException(String message) {
		super(message);
	}

}
