package com.ers.exceptions;

/**
 * Custom exception to create an exception when a user attempts to access the
 * server without proper authentication.
 * 
 * @author Jose Rivera
 *
 */
public class UnauthenticatedAccessException extends Exception {

	/**
	 * Generated Serial Version ID. Generated by Java.
	 */
	private static final long serialVersionUID = -10566931042122659L;

	public UnauthenticatedAccessException(String message) {
		super(message);
	}

}
