package com.ers.exceptions;

/**
 * User defined exception to be thrown if an unauthenticated access attempt is
 * detected.
 * 
 * @author Jose Rivera
 */
public class UnauthenticatedAccessException extends Exception {

	/**
	 * Generated Serial Version ID. Generated by Java.
	 */
	private static final long serialVersionUID = -10566931042122659L;

	/**
	 * Exception constructor to create an exception.
	 * 
	 * @param message The message to display that is sent to the super class.
	 */
	public UnauthenticatedAccessException(String message) {
		super(message);
	}

}
