package com.ers.servlets;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;

import com.ers.models.Reimbursement;
import com.ers.services.ReimbursementService;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * Servlet implementation class SubmitReimbursementServlet. This servlet will
 * help to submit a reimbursement to the database.
 * 
 * @author Jose Rivera
 */
@WebServlet("/submit")
public class SubmitReimbursementServlet extends HttpServlet {

	/**
	 * Generated Serial Version ID. Generated by Java.
	 */
	private static final long serialVersionUID = -6990965405063687615L;

	private static final Logger LOG = Logger.getLogger(SubmitReimbursementServlet.class);

	private ReimbursementService reimbursementService = new ReimbursementService();

	/**
	 * POST method to accept reimbursement information in order to create a
	 * reimbursement. Will accept the reimbursement information in JSON and send the
	 * details to the reimbursement service to create a reimbursement.
	 */
	@Override
	protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws IOException, ServletException {

		try {

			// Get the object mapper
			ObjectMapper objectMapper = new ObjectMapper();

			// Read the values for a reimbursement
			Reimbursement newReimbursement = objectMapper.readValue(req.getInputStream(), Reimbursement.class);

			// Check our reimbursement
			if (newReimbursement == null) {
				LOG.warn("In SubmitReimbursementServlet.doPost():: Reimbursement was null");
				resp.setStatus(400);
				return;
			}

			// Send to service to add to database
			Reimbursement reimbursement = reimbursementService.add(newReimbursement);

			// Check our newly added reimbursement
			if (reimbursement == null) {
				LOG.warn("In SubmitReimbursementServlet.doPost():: Newly added reimbursement was null");
				resp.setStatus(400);
				return;
			}

			// Our reimbursement was successfully added
			resp.setStatus(200);

			// Send our user object back to client
			PrintWriter printWriter = resp.getWriter();
			resp.setContentType("application/json");

			// Write our reimbursement back as JSON
			String reimbursementJson = objectMapper.writeValueAsString(reimbursement);
			printWriter.write(reimbursementJson);

		} catch (IllegalStateException ise) {
			LOG.error(ise.getMessage());
		} catch (JsonParseException jpe) {
			LOG.error(jpe.getMessage());
		} catch (JsonMappingException jmp) {
			LOG.error(jmp.getMessage());
		} catch (IOException ioe) {
			LOG.error(ioe.getMessage());
		} catch (Exception e) {
			LOG.error(e.getMessage());
		}
	}
}
