package com.ers.servlets;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;

import com.ers.util.RequestViewHelper;

/**
 * Servlet implementation class ViewServlet. This servlet will help switching
 * views for the front end requests. Will accept all requests that have '.view'
 * in the uri.
 * 
 * @author Jose Rivera
 */
@WebServlet("*.view")
public class ViewServlet extends HttpServlet {

	/**
	 * Generated Serial Version ID. Generated by Java.
	 */
	private static final long serialVersionUID = -786582522394880612L;

	private static final Logger LOG = Logger.getLogger(ViewServlet.class);

	/**
	 * GET method to change the view on the front end. This servlet will handle all
	 * request that have the uri .view in order to respond with the correct view to
	 * update the page with. Will communicate with a request view helper class to
	 * determine the view to switch to.
	 */
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException, ServletException {

		String view = RequestViewHelper.process(req);

		try {
			req.getRequestDispatcher(view).forward(req, resp);
		} catch (Exception e) {
			LOG.error(e.getMessage());
		}
	}
}
